const express = require("express")
const database = require("./database")

const app = express()
const PORT = 8000
app.use(require("cors")())
app.use(express.json())
app.post("/listCreate",require("./list/create/route"))
app.post("/listAddItem",require("./item/add/route"))
app.post("/listDelete",require("./list/delete/route"))
app.post("/listDeleteItem",require("./item/delete/route"))
app.get("/listGetData",require("./list/get/route"))
app.post("/listInviteMember",require("./list/inviteMember/route"))
app.post("/listKickMember",require("./list/kickMember/route"))
app.get("/listList",require("./list/list/route"))
app.post("/listRename",require("./list/rename/route"))
app.post("/listSetArchiveStatus",require("./list/setArchiveStatus/route"))
app.post("/userValidate",require("./user/validate/route"))
app.post("/listSetItemStatus",require("./item/setArchiveStatus/route"))
app.post("/listRenameItem",require("./item/rename/route"))
app.get("/userList",require("./userList/route"))
app.listen(PORT,() =>{
    console.log(`ShoppingList server listening on port ${PORT}`)
    database.connect()
})
process.on("beforeExit",_ => database.close())