const express = require("express")

const app = express()
const PORT = 8000
app.use(require("cors")())
app.use(express.json())
app.use("/listCreate",require("./listCreate/listCreateRouter"))
app.use("/listAddItem",require("./listAddItem/listAddItemRouter"))
app.use("/listDelete",require("./listDelete/listDeleteRouter"))
app.use("/listDeleteItem",require("./listDeleteItem/listDeleteItemRouter"))
app.use("/listGetData",require("./listGetData/listGetDataRouter"))
app.use("/listInviteMember",require("./listInviteMember/listInviteMemberRouter"))
app.use("/listKickMember",require("./listKickMember/listKickMemberRouter"))
app.use("/listList",require("./listList/listListRouter"))
app.use("/listRename",require("./listRename/listRenameRouter"))
app.use("/listSetArchiveStatus",require("/listSetArchiveStatus"))
app.use("/userValidate",require("./userValidate/userValidateRouter"))
app.use("/listSetItemStatus",require("./listSetItemStatus/listSetItemStatusRouter"))
app.use("/listRenameItem",require("./listRenameItem/listRenameItemRouter"))
app.listen(PORT,() => console.log('ShoppingList server listening ${port}'))